//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WelcomeApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The UA Configuration Tool provides options for managing applications, certificate" +
            " trusts, and COM/UA interoperability.")]
        public string ConfigAppDescription {
            get {
                return ((string)(this["ConfigAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UA Configuration Tool")]
        public string ConfigAppName {
            get {
                return ((string)(this["ConfigAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPC UA DA Server is a light-weight application that provides access to readable/w" +
            "riteble data.")]
        public string DAServerAppDescription {
            get {
                return ((string)(this["DAServerAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DA Server")]
        public string DAServerAppName {
            get {
                return ((string)(this["DAServerAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPC UA DA Client is a light-weight application that provides minimal capabilities" +
            " and merely demonstrates the simple data-acquisition from an OPC UA DA Server.")]
        public string DAClientAppDescription {
            get {
                return ((string)(this["DAClientAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DA Client")]
        public string DAClientAppName {
            get {
                return ((string)(this["DAClientAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This Historical Data Server is a purpose-built application that serves static and" +
            "/or dynamic historical data to clients.")]
        public string HADServerAppDescription {
            get {
                return ((string)(this["HADServerAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HA Data Server")]
        public string HADServerAppName {
            get {
                return ((string)(this["HADServerAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The HA Data Client is a purpose-built application for demonstrating OPC Historica" +
            "l Data.")]
        public string HADClientAppDescription {
            get {
                return ((string)(this["HADClientAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HA Data Client")]
        public string HADClientAppName {
            get {
                return ((string)(this["HADClientAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This Historical Events Server is a purpose-built application that serves historic" +
            "al events information to clients.")]
        public string HAServerAppDescription {
            get {
                return ((string)(this["HAServerAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HE Data Server")]
        public string HAServerAppName {
            get {
                return ((string)(this["HAServerAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The Historical Events Client is a purpose-built client that demonstrates the use " +
            "of Historical Events.")]
        public string HAEClientAppDescription {
            get {
                return ((string)(this["HAEClientAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HE Data Client")]
        public string HAEClientAppName {
            get {
                return ((string)(this["HAEClientAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This Alarms & Conditions Server is a purpose-built application raises alarms and " +
            "events information to clients")]
        public string ACServerAppDescription {
            get {
                return ((string)(this["ACServerAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AC Server")]
        public string ACServerAppName {
            get {
                return ((string)(this["ACServerAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alarms and Condition Client is a purpose-built client for demonstrating OPC UA Al" +
            "arms & Conditions.")]
        public string ACClientAppDescription {
            get {
                return ((string)(this["ACClientAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AC Client")]
        public string ACClientAppName {
            get {
                return ((string)(this["ACClientAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Discover Server provides a list of available OPC UA applications to any OPC appli" +
            "cation that queries it")]
        public string LDSAppDescription {
            get {
                return ((string)(this["LDSAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Discovery Server")]
        public string LDSAppName {
            get {
                return ((string)(this["LDSAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UA Generic Server combines the features of several server profiles")]
        public string GenServerAppDescription {
            get {
                return ((string)(this["GenServerAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Generic Server")]
        public string GenServerAppName {
            get {
                return ((string)(this["GenServerAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UA Generic Client combines the features of several client profiles")]
        public string GenClientAppDescription {
            get {
                return ((string)(this["GenClientAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Generic Client")]
        public string GenClientAppName {
            get {
                return ((string)(this["GenClientAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The Reference Server is a purpose built server used during the development and te" +
            "sting of the Unified Architecture")]
        public string RefServerAppDescription {
            get {
                return ((string)(this["RefServerAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reference Server")]
        public string RefServerAppName {
            get {
                return ((string)(this["RefServerAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The Reference Client is a very light-weight Client that offers minimal functional" +
            "ity. It is a purpose-built Client for connecting directly to the Reference Serve" +
            "r to consume data.")]
        public string RefClientAppDescription {
            get {
                return ((string)(this["RefClientAppDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reference Client")]
        public string RefClientAppName {
            get {
                return ((string)(this["RefClientAppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\overview_-_reference_client.htm")]
        public string RefClientHelp {
            get {
                return ((string)(this["RefClientHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\overview_referenceServer.htm")]
        public string RefServerHelp {
            get {
                return ((string)(this["RefServerHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\ua_sample_client.htm")]
        public string GenClientHelp {
            get {
                return ((string)(this["GenClientHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\ua_sample_server.htm")]
        public string GenServerHelp {
            get {
                return ((string)(this["GenServerHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\local_discovery_server_(lds).htm")]
        public string LDSHelp {
            get {
                return ((string)(this["LDSHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\acclientoverview.htm")]
        public string ACClientHelp {
            get {
                return ((string)(this["ACClientHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\acserveroverview.htm")]
        public string ACServerHelp {
            get {
                return ((string)(this["ACServerHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\haeventsclientoverview.htm")]
        public string HAEClientHelp {
            get {
                return ((string)(this["HAEClientHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\haeventsserveroverview.htm")]
        public string HAEServerHelp {
            get {
                return ((string)(this["HAEServerHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\haclientoverview.htm")]
        public string HADClientHelp {
            get {
                return ((string)(this["HADClientHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\haserveroverview.htm")]
        public string HADServerHelp {
            get {
                return ((string)(this["HADServerHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\daclientoverview.htm")]
        public string DAClientHelp {
            get {
                return ((string)(this["DAClientHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\daserveroverview.htm")]
        public string DAServerHelp {
            get {
                return ((string)(this["DAServerHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\ua_configuration_tool.htm")]
        public string ConfigHelp {
            get {
                return ((string)(this["ConfigHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Opc.Ua.ConfigurationTool.exe")]
        public string ConfigProcess {
            get {
                return ((string)(this["ConfigProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quickstarts.dataaccessserver.exe")]
        public string DAServer {
            get {
                return ((string)(this["DAServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quickstarts.dataaccessclient.exe")]
        public string DAClient {
            get {
                return ((string)(this["DAClient"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quickstarts.historicalaccessserver.exe")]
        public string HADServerProcess {
            get {
                return ((string)(this["HADServerProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quickstarts.historicalaccessclient.exe")]
        public string HADClientProcess {
            get {
                return ((string)(this["HADClientProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quickstarts.historicaleventsserver.exe")]
        public string HAEServerProcess {
            get {
                return ((string)(this["HAEServerProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quickstarts.historicaleventsclient.exe")]
        public string HAEClientProcess {
            get {
                return ((string)(this["HAEClientProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quickstarts.alarmconditionserver.exe")]
        public string ACServerProcess {
            get {
                return ((string)(this["ACServerProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quickstarts.alarmconditionclient.exe")]
        public string ACClientProcess {
            get {
                return ((string)(this["ACClientProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPC.ua.sampleserver.exe")]
        public string GenServerProcess {
            get {
                return ((string)(this["GenServerProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPC.ua.sampleclient.exe")]
        public string GenClientProcess {
            get {
                return ((string)(this["GenClientProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quickstarts.referenceserver.exe")]
        public string RefServerProcess {
            get {
                return ((string)(this["RefServerProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("quickstarts.referenceclient.exe")]
        public string RefClientProcess {
            get {
                return ((string)(this["RefClientProcess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webhelp\\welcome.htm")]
        public string WelcomeHelp {
            get {
                return ((string)(this["WelcomeHelp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPC.ua.discoveryserver.exe")]
        public string LDSProcess {
            get {
                return ((string)(this["LDSProcess"]));
            }
        }
    }
}
